### ISSUE TITLE
HelloMaui build error

### ISSUE THREAD

**Issue by bhavesh4asi** [dotnet/net6-mobile-samples#102]
Hello Team,

I installed Preview1, now I installed Preview2. I was able to run iOS and Android project without any issue but everytime when I try to build HelloMaui project, dotnet is crashing. Here is a crash log,

Process:               dotnet [45008]
Path:                  /usr/local/share/dotnet/dotnet
Identifier:            dotnet
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        dotnet [45006]
Responsible:           Terminal [2397]
User ID:               501

Date/Time:             2021-03-17 15:43:21.008 -0700
OS Version:            macOS 11.2.1 (20D74)
Report Version:        12
Anonymous UUID:        7AB70660-25A8-5B42-2565-6231F91B77B5

Sleep/Wake UUID:       DBDCE2AC-AC5D-4CAF-A3CB-B4E8D57A4A6F

Time Awake Since Boot: 840000 seconds
Time Since Wake:       7800 seconds

System Integrity Protection: enabled

Crashed Thread:        17  .NET ThreadPool Worker

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2

kernel messages:

VM Regions Near 0x10a3aed20 (cr2):
    __LINKEDIT                  10a00d000-10a034000    [  156K] r--/rwx SM=COW  /usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.0-preview.2.21154.6/libhostpolicy.dylib
--> __TEXT                      10a034000-10a538000    [ 5136K] r-x/rwx SM=COW  /usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.0-preview.2.21154.6/libcoreclr.dylib
    __DATA                      10a538000-10a53e000    [   24K] rw-/rwx SM=COW  /usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.0-preview.2.21154.6/libcoreclr.dylib

Application Specific Information:
dyld: in dlopen()
/Users/bhavesh/development/MAUI/net6-mobile-samples-main/packages/microsoft.maui.resizetizer/6.0.100-preview.2.174/buildTransitive/libSkiaSharp.dylib

**Comment by jonathanpeppers** [comment]
/cc @mattleibow

@bhavesh4asi can you attach a build log?

```
$ dotnet build HelloMaui -bl
```
`-bl` will create a `msbuild.binlog` file you should be able to zip up and attach here, thanks!

**Comment by bhavesh4asi** [comment]
I am not sure what changed but I try to run it again after mac restart and problem resolved. Thank you for your help.

**Comment by jonathanpeppers** [comment]
Let us know if it happens again and get a log for us, thanks!
