### ISSUE TITLE
Build Issue with Samples

### ISSUE THREAD

**Issue by Russ-McClelland** [dotnet/net6-mobile-samples#106]
MacOS
After updating VS, XCode, downloading and installing all the packages from this list (https://github.com/dotnet/net6-mobile-samples), and rebooting, I get the following error following the readme instructions:

dotnet build HelloMaui -t:Run -f net6.0-maccatalyst
Microsoft (R) Build Engine version 16.10.0-preview-21126-01+6819f7ab0 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/Projects/Microsoft/net6-mobile-samples/HelloMaui/HelloMaui.csproj : error MSB4057: The target "Run" does not exist in the project.

**Comment by jonathanpeppers** [comment]
You need `--no-restore` as described here:

https://github.com/dotnet/net6-mobile-samples#net-maui

This should be fixed in the next preview: https://github.com/dotnet/sdk/issues/15485
