### ISSUE TITLE
Add some kind of completion feedback to the iOS workload installer.

### ISSUE THREAD

**Issue by drchilds** [dotnet/net6-mobile-samples#113]
As it runs now, the iOS workload installer completes without any feedback. Please add at least a small dialog indicating success or failure.

**Comment by jonathanpeppers** [comment]
The current installers are temporary.

We will eventually be using `dotnet workload install` commands, which are still a WIP.

I think things will change completely here, by the time .NET 6 GA ships. You'll be happy with what is planned.
