### ISSUE TITLE
NETSDK1139 when restoring any macOS project

### ISSUE THREAD

**Issue by wjk** [dotnet/net6-mobile-samples#135]
I have version 6.0.100-preview.3.21202.5 of the .NET SDK installed. I have created a sample project using the `dotnet new macos -o macos_test` command. But when I run `dotnet restore` on that project, I get the following error (wrapped for readability):

```
/usr/local/share/dotnet/sdk/6.0.100-preview.3.21202.5/Sdks/Microsoft.NET.Sdk/
targets/Microsoft.NET.TargetFrameworkInference.targets(109,5): error NETSDK1139:
The target platform identifier macos was not recognized.
[/Volumes/Sources/AvaloniaTest/AvaloniaTest/AvaloniaTest.csproj]
```

This occurs on any project using that TFM. What can be done about this?

-------

[msbuild.binlog](https://github.com/dotnet/net6-mobile-samples/files/6330037/msbuild.binlog.zip)

`dotnet --info` output:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.2
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-preview.3.21202.5/

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  5.0.202 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.3.21202.5 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Divyeshpatel6073** [comment]
I have also same issue 
But i am using windows 10

error NETSDK1139: The target platform identifier ios was not recognized.

**Comment by jonathanpeppers** [comment]
@wjk do you have this file:
```
__EnableWorkloadResolverSentinelPath = /usr/local/share/dotnet/sdk/6.0.100-preview.3.21202.5/EnableWorkloadResolver.sentinel
```
If not, just create it (it is a feature flag). The Android workload creates this file for you, but the other workloads don't. We should hopefully be removing the need for it completely in the next preview.

@Divyeshpatel6073 your issue might be the same, but you would need to check the build log to know what file it's looking for.

**Comment by wjk** [comment]
@jonathanpeppers Worked great! Thanks!

**Comment by Divyeshpatel6073** [comment]
@jonathanpeppers where am i check build log file?

**Comment by jonathanpeppers** [comment]
@Divyeshpatel6073 if you are running `dotnet build` at the command-line it is probably:

    C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\EnableWorkloadResolver.sentinel

You could also try installing the Android workload to see if that fixes it for you.

**Comment by Divyeshpatel6073** [comment]
Now getting this error

![image](https://user-images.githubusercontent.com/20996843/115274468-52052a00-a15e-11eb-982b-2680938edb43.png)

**Comment by jonathanpeppers** [comment]
@Divyeshpatel6073 can you file a new issue? Add `-bl` to your command and attach the `msbuild.binlog` file it creates. Thanks!

**Comment by Divyeshpatel6073** [comment]
@jonathanpeppers 
hello sir I have to create a new issue 
please check it
NETSDK1139 when restoring my project #136
