### ISSUE TITLE
NU1202 when restoring my project

### ISSUE THREAD

**Issue by Divyeshpatel6073** [dotnet/net6-mobile-samples#136]
@jonathanpeppers
I have version 6.0.100-preview.3.21215.22 of the .NET SDK installed. I have created a sample project using the dotnet new maui -n hello command. But when I run dotnet restore on that project, I get the following error (wrapped for readability):

msbuild.binlog
![image](https://user-images.githubusercontent.com/20996843/115275838-f0de5600-a15f-11eb-8a06-46813e04de2f.png)

maui-check
![image](https://user-images.githubusercontent.com/20996843/115275963-166b5f80-a160-11eb-8e06-7297b7f9337c.png)

occure error NU1202
![image](https://user-images.githubusercontent.com/20996843/115275711-c7252f00-a15f-11eb-8e5c-f3e86012d3d6.png)

**Comment by jonathanpeppers** [comment]
Did you upload the `msbuild.binlog` file? You'll probably have to zip it, before Github will allow it.

**Comment by Divyeshpatel6073** [comment]
Ok sir @jonathanpeppers 
I will attach zip file in 10 min

**Comment by Divyeshpatel6073** [comment]
How to create msbuild.binlog file?
@jonathanpeppers

**Comment by Divyeshpatel6073** [comment]
[msbuild.ProjectImports.zip](https://github.com/dotnet/net6-mobile-samples/files/6338528/msbuild.ProjectImports.zip)

**Comment by Divyeshpatel6073** [comment]
@jonathanpeppers 
Here is my binlog file 

https://github.com/dotnet/net6-mobile-samples/files/6338670/msbuild.binlog.2.zip

**Comment by jonathanpeppers** [comment]
Your project has: `<PackageReference Include="Microsoft.Maui" Version="6.0.100-preview.3.322+sha.b83f98aca-azdo.4633246" />`

Does it work if you use the version in these samples:

https://github.com/dotnet/net6-mobile-samples/blob/46129f85d78b55589280e5bb0ea399bb1dd72167/HelloMaui/HelloMaui.csproj#L17

**Comment by Divyeshpatel6073** [comment]
Thank you sir
it is work but I have another issue 
error XA1018: Specified AndroidManifest file does not exist: F:\Others\MAUI\hello2\AndroidManifest.xml

**Comment by Divyeshpatel6073** [comment]
i am using this package & it shows me this error see image
`<PackageReference Include="Microsoft.Maui" Version="6.0.100-preview.3.322" />`

![image](https://user-images.githubusercontent.com/20996843/115439790-99f28280-a22c-11eb-8de0-cbeaa07c805c.png)

**Comment by Divyeshpatel6073** [comment]
> Your project has: `<PackageReference Include="Microsoft.Maui" Version="6.0.100-preview.3.322+sha.b83f98aca-azdo.4633246" />`
> 
> Does it work if you use the version in these samples:
> 
> https://github.com/dotnet/net6-mobile-samples/blob/46129f85d78b55589280e5bb0ea399bb1dd72167/HelloMaui/HelloMaui.csproj#L17

no sir it does not work it shows me this error
![image](https://user-images.githubusercontent.com/20996843/115440140-08cfdb80-a22d-11eb-9214-b74294eeb502.png)

**Comment by Divyeshpatel6073** [comment]
Hello 
anybody have this issue?
Please help me..

**Comment by Micaredboys** [comment]
Micaredboys.github.io

**Comment by Divyeshpatel6073** [comment]
Thank you for your advice @jonathanpeppers
And i am your big fan

My system has 
Microsoft.Android.sdk 
old version.
I uninstalled this version 

Install new version of **Microsoft.Android.sdk with version(11.0.200-preview:3.196)**

**And my problem has solved**


Let me tell you 
Android version 8.0 support or not?

**Comment by Divyeshpatel6073** [comment]
Android version 8.1 support or not?
Because 

When i am run my simulator it is install and working fine
But When i am run my device it shows me this error 
**ADB0020** 

**My device detail**
Device : Lg 
Api - 27

**Comment by jonathanpeppers** [comment]
@Divyeshpatel6073 the `IncompatibleCpuAbiException` error means your device might be 32-bit?

Try adding `-r android-arm` to the command-line or put `<RuntimeIdentifier>android-arm</RuntimeIdentifier>`.

You can also put multiple if you want to use the x86 emulator:

```xml
<RuntimeIdentifiers>android-arm;android-x86</RuntimeIdentifiers>
```

**Comment by Divyeshpatel6073** [comment]
@jonathanpeppers 
Thank you for your advice
it's run 
tell me how to debug my application?

**Comment by jonathanpeppers** [comment]
We have some examples for Visual Studio on Windows and VS Code here: https://github.com/dotnet/net6-mobile-samples#using-ides

James Montemagno also made a nice video: https://www.youtube.com/watch?v=Ppb4PnpWrjg

**Comment by jonathanpeppers** [comment]
@jwoeste your error above usually means your workloads are hosed, sorry! You could follow this to get back to a clean state:

https://gist.github.com/jonathanpeppers/63beb491a9185ac06710261536cc35c9

If you want to get traction on this problem, I would file an issue here with more details:

https://github.com/dotnet/sdk/issues

**Comment by jonathanpeppers** [comment]
Any chance a `global.json` file is involved? If there is one in the current directory, is that causing problems?

**Comment by jwoeste** [comment]
no global.json involved. Same thing regardless of creating project from cli (dotnet new maui -o mauitest) or using template in VS2022 for Mac (both 17.4 and 17.5 preview). Same also occurs in jet brains rider. 

Only way to build and run is from cli.

**Comment by jonathanpeppers** [comment]
If CLI works, then this is an issue in VS Mac. I'd use the "Send Feedback" button, and maybe someone can help there.
