### ISSUE TITLE
where is document, I did not see the document

### ISSUE THREAD

**Issue by mingyouzhu** [dotnet/net6-mobile-samples#141]
where is document, I did not see the document

**Comment by mingyouzhu** [comment]
how to create a Maui project?

**Comment by VladislavAntonyuk** [comment]
https://github.com/dotnet/net6-mobile-samples/issues/116
May be a bit outdated but should be enough for the overview: https://vladislavantonyuk.azurewebsites.net/articles/The-first-project-with-.NET-MAUI

**Comment by jonathanpeppers** [comment]
The dotnet/maui repo has some initial getting started instructions here:

https://github.com/dotnet/maui/wiki

Hope that helps, thanks.

**Comment by shawyunz** [comment]
https://docs.microsoft.com/en-us/dotnet/maui/
