### ISSUE TITLE
Does not run in Android emulator

### ISSUE THREAD

**Issue by jfacoustic** [dotnet/net6-mobile-samples#50]
Both HelloAndroid and HelloForms successfully build, but they don't attach to my android emulator.  The output for `dotnet build HelloForms/HelloForms.csproj -t:Run -p:TargetFramework=net6.0-android` is

```
Microsoft (R) Build Engine version 16.9.0-preview-20561-01+56ab63409 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Users\joshua\Documents\net6-samples\HelloForms\HelloForms.csproj (in 1.03 min).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  HelloForms -> C:\Users\joshua\Documents\net6-samples\HelloForms\bin\Debug\net6.0-android\HelloForms.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:02:14.82
``` 

Am I missing a step?

**Comment by VladislavAntonyuk** [comment]
Probably you should use dotnet run

**Comment by jonathanpeppers** [comment]
@jfacoustic sorry for the delay, everyone is off for the holidays. Your command should work did you try running `adb devices` to see if your emulator is connected? If it shows no devices restart the emulator, just using the device manager in Visual Studio with the current Xamarin workload.

The `Run` target should work if adb is connected to a single device or emulator.

**Comment by jonathanpeppers** [comment]
Try the latest builds on `main` for Preview 2, and let us know if you run into any issues, thanks!
