### ISSUE TITLE
Add macOS sample?

### ISSUE THREAD

**Issue by wjk** [dotnet/net6-mobile-samples#51]
What the title says. I only use Xamarin.Mac, so that technology is what I am most interested in.

**Comment by jonathanpeppers** [comment]
I think the missing piece here is a Microsoft.Android.MacOS.Sdk, which I don't think we have yet.

@rolfbjarne is there a way to use Xamarin.Mac with the current packages?

**Comment by rolfbjarne** [comment]
We just need a very simple macOS app, here's one of our test apps we could adapt: https://github.com/xamarin/xamarin-macios/tree/0e79b58fa8b07b0195ca611c7f1227036e44127b/tests/dotnet/MyCocoaApp

**Comment by VladislavAntonyuk** [comment]
I think it is already implemented in develop branch

**Comment by jonathanpeppers** [comment]
@VladislavAntonyuk there is a MacCatalyst sample (this is iOS/UIKit running on Mac), but we could add a Mac (AppKit) sample, too.
