### ISSUE TITLE
Hello Android App Crashes as soon as it launches.

### ISSUE THREAD

**Issue by parthchopra** [dotnet/net6-mobile-samples#62]
I briefly see the activity but app crashes right after that.

**Comment by jonathanpeppers** [comment]
Could you be hitting the `Known Issue` listed here?

https://github.com/dotnet/net6-mobile-samples/releases/tag/6.0.1xx-preview1

Try either specifying the runtime identifier for your device:

```xml
<PropertyGroup>
  <!--For an arm64 device-->
  <RuntimeIdentifier>android.21-arm64</RuntimeIdentifier>
  <!--For an x86 emulator-->
  <RuntimeIdentifier>android.21-x86</RuntimeIdentifier>
</PropertyGroup>
```

Or disabling fast deployment also might solve it:

```xml
<PropertyGroup>
  <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
</PropertyGroup>
```

If that doesn't work, can you attach [`adb logcat` output](https://docs.microsoft.com/xamarin/android/deploy-test/debugging/android-debug-log#accessing-from-the-command-line)? Thanks!

**Comment by parthchopra** [comment]
Disabling fast deployment worked. Should I add it in the samples project and create a PR?

**Comment by jonathanpeppers** [comment]
Sure, thanks.

We will have new builds on the [develop](https://github.com/dotnet/net6-mobile-samples/tree/develop) branch soon where it will work.
