### ISSUE TITLE
MSB4057: The target "Install" does not exist in the project

### ISSUE THREAD

**Issue by PaulAnderson02** [dotnet/net6-mobile-samples#66]
Im facing the issue mentioned in the title when deploying the "HelloForms" project in Android.

version: VS 2019 16.9 Preview 4.

Done all workarounds mentioned for deploying the sample.

> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.microsoft.net6.helloforms/crc6454ad0c421ff6d919.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.microsoft.net6.helloforms/crc6454ad0c421ff6d919.MainActivity }
Error type 3
Error: Activity class {com.microsoft.net6.helloforms/crc6454ad0c421ff6d919.MainActivity} does not exist.
Failed to launch android application

**Comment by PaulAnderson02** [comment]
Got it resolved

**Comment by jonathanpeppers** [comment]
If someone is running into this: https://github.com/dotnet/net6-mobile-samples#xamarinforms--maui

> NOTE: You may need to add the `--no-restore` switch until https://github.com/dotnet/sdk/issues/15485 is resolved.
