### ISSUE TITLE
error MSB4057 on Maui build

### ISSUE THREAD

**Issue by RsZoli** [dotnet/net6-mobile-samples#85]
Executing the "**dotnet build HelloMaui -t:Run -f net6.0-android**" command results in the following error: "**error MSB4057: The target "Run" does not exist in the project.**"

[https://i.imgur.com/SG96wBr.png](https://i.imgur.com/SG96wBr.png)

.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.2.21155.3
 Commit:    1a9103db2d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.21327
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

.NET SDKs installed:
  5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.2.21155.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.2.21154.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by VladislavAntonyuk** [comment]
Add —no-restore

**Comment by RsZoli** [comment]
> Add —no-restore

That means: 
C:\Users\RsZoli\Documents\net6-mobile-samples-develop\packages\microsoft.maui.resizetizer\6.0.100-preview.2.122\buildTransitive\Microsoft.Maui.Resizetizer.targets(332,9): error : Failed to Convert SVG to Android Drawable: EXCEPTION in parsing c:\Users\RsZoli\Documents\net6-mobile-samples-develop\HelloMaui\Resources\AppIcons\appiconfg.svg: [c:\Users\RsZoli\Documents\net6-mobile-samples-develop\HelloMaui\HelloMaui.csproj]
C:\Users\RsZoli\Documents\net6-mobile-samples-develop\packages\microsoft.maui.resizetizer\6.0.100-preview.2.122\buildTransitive\Microsoft.Maui.Resizetizer.targets(332,9): error : error in parsing "m 105.50037,281.60863 " in [c:\Users\RsZoli\Documents\net6-mobile-samples-develop\HelloMaui\Resources\AppIcons\appiconfg.svg] [c:\Users\RsZoli\Documents\net6-mobile-samples-develop\HelloMaui\HelloMaui.csproj]
C:\Users\RsZoli\Documents\net6-mobile-samples-develop\packages\microsoft.maui.resizetizer\6.0.100-preview.2.122\buildTransitive\Microsoft.Maui.Resizetizer.targets(332,9): error : One or more errors occurred. (Failed to Convert SVG to Android Drawable: EXCEPTION in parsing c:\Users\RsZoli\Documents\net6-mobile-samples-develop\HelloMaui\Resources\AppIcons\appiconfg.svg: [c:\Users\RsZoli\Documents\net6-mobile-samples-develop\HelloMaui\HelloMaui.csproj]
C:\Users\RsZoli\Documents\net6-mobile-samples-develop\packages\microsoft.maui.resizetizer\6.0.100-preview.2.122\buildTransitive\Microsoft.Maui.Resizetizer.targets(332,9): error : error in parsing "m 105.50037,281.60863 " in [c:\Users\RsZoli\Documents\net6-mobile-samples-develop\HelloMaui\Resources\AppIcons\appiconfg.svg]) [c:\Users\RsZoli\Documents\net6-mobile-samples-develop\HelloMaui\HelloMaui.csproj]

**Comment by jonathanpeppers** [comment]
@RsZoli can you attach a `.binlog`? Add `-bl` to your command and upload the `msbuild.binlog` here, thanks!

**Comment by RsZoli** [comment]
> @RsZoli can you attach a `.binlog`? Add `-bl` to your command and upload the `msbuild.binlog` here, thanks!

Of course!

dotnet build HelloMaui -t:Run -f net6.0-android --no-restore -bl: [https://drive.google.com/file/d/1JjlCK6WMaQDnIgIanKeF9BuSVEaSsEFj/view?usp=sharing](https://drive.google.com/file/d/1JjlCK6WMaQDnIgIanKeF9BuSVEaSsEFj/view?usp=sharing)

dotnet build HelloMaui -t:Run -f net6.0-android -bl: [https://drive.google.com/file/d/1md4eIMaCJXdtM48JuSa3H1llpAyTVO6F/view?usp=sharing](https://drive.google.com/file/d/1md4eIMaCJXdtM48JuSa3H1llpAyTVO6F/view?usp=sharing)

**Comment by jonathanpeppers** [comment]
Try cleaning everything and rebuilding:
```
> git clean -dxf
> dotnet build HelloMaui
> dotnet build HelloMaui -t:Run -f net6.0-android --no-restore
```

@mattleibow do you see anything with the log above? It seems like it can't parse the `.svg` file?

```
Microsoft.Maui.Resizetizer.targets(332,9): Failed to Convert SVG to Android Drawable: EXCEPTION in parsing c:\Users\RsZoli\Documents\net6-mobile-samples-develop\HelloMaui\Resources\AppIcons\appiconfg.svg:
error in parsing "m 105.50037,281.60863 " in [c:\Users\RsZoli\Documents\net6-mobile-samples-develop\HelloMaui\Resources\AppIcons\appiconfg.svg] [c:\Users\RsZoli\Documents\net6-mobile-samples-develop\HelloMaui\HelloMaui.csproj]
Microsoft.Maui.Resizetizer.targets(332,9): One or more errors occurred. (Failed to Convert SVG to Android Drawable: EXCEPTION in parsing c:\Users\RsZoli\Documents\net6-mobile-samples-develop\HelloMaui\Resources\AppIcons\appiconfg.svg:
error in parsing "m 105.50037,281.60863 " in [c:\Users\RsZoli\Documents\net6-mobile-samples-develop\HelloMaui\Resources\AppIcons\appiconfg.svg]) [c:\Users\RsZoli\Documents\net6-mobile-samples-develop\HelloMaui\HelloMaui.csproj]
```

**Comment by RsZoli** [comment]
> Try cleaning everything and rebuilding:

It's the same.

**Comment by VladislavAntonyuk** [comment]
Replace the svg image with your own image and try again

**Comment by jonathanpeppers** [comment]
We think this is fixed in: https://github.com/dotnet/maui/commit/45f9d4796eb8070f7d398c0764c5377bc665298d

We will get a new build of Maui here, which will hopefully fix it.

**Comment by RsZoli** [comment]
> @RsZoli can you try the latest on the main branch now and let us know?

I have tried it, the following error occures: "C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(871,5): error MSB3073: The command "c:\Users\RsZoli\Documents\net6-mobile-samples-main\HelloMaui\bin\Debug\net6.0-android\HelloMaui.exe " exited with code 3. [c:\Users\RsZoli\Documents\net6-mobile-samples-main\HelloMaui\HelloMaui.csproj]"

**Comment by jonathanpeppers** [comment]
This looks like you don't have the latest Android workload, can you check that you have:

https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4534967/main/f4d8fe238b15eadfc7842749bf13e5fca3e2f2d2/Microsoft.NET.Workload.Android.11.0.200.148.msi

**Comment by RsZoli** [comment]
> This looks like you don't have the latest Android workload, can you check that you have:
> 
> https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4534967/main/f4d8fe238b15eadfc7842749bf13e5fca3e2f2d2/Microsoft.NET.Workload.Android.11.0.200.148.msi

I had that version, but i used the installer you linked and did a repair, it is working now, thank you!

**Comment by jonathanpeppers** [comment]
Ok, great, thanks!
